spring.application.name=Intenship-Project
spring.datasource.url=jdbc:mysql://localhost:3306/golf_platform
spring.datasource.username=root
spring.datasource.password=131202
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=12345678901234567890123456789012
app.jwt.expiration=86400000
